name: Pushes to Branch

on:
  push:
    branches: [ fix/imagemetadata_for_api_25 ]

env:
  GITHUB_USERNAME: ${{ secrets.GIT_USER }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-20.04
    container: androidsdk/android-30:latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'fix/imagemetadata_for_api_25'
      - name: Setup NDK
        run: |
          wget --quiet https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
          mkdir /opt/android-sdk-linux/ndk
          unzip -q android-ndk-r17b-linux-x86_64.zip -d /opt/android-sdk-linux/ndk
      - name: Setup Properties
        run: |
          echo "ndk.dir=/opt/android-sdk-linux/ndk/android-ndk-r17b" >> local.properties
      - name: Make Build Local
        run: |
          ./gradlew install
      - name: Upload to Nexus
        run: |
          curl -v -u ${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN} --upload-file ~/.m2/repository/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT-javadoc.jar https://nexus-prod-mercury.dnitv.net/repository/maven-snapshots/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT-javadoc.jar
          curl -v -u ${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN} --upload-file ~/.m2/repository/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT.pom https://nexus-prod-mercury.dnitv.net/repository/maven-snapshots/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT.pom
          curl -v -u ${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN} --upload-file ~/.m2/repository/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT-sources.jar https://nexus-prod-mercury.dnitv.net/repository/maven-snapshots/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT-sources.jar
          curl -v -u ${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN} --upload-file ~/.m2/repository/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/maven-metadata-local.xml https://nexus-prod-mercury.dnitv.net/repository/maven-snapshots/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/maven-metadata-local.xml
          curl -v -u ${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN} --upload-file ~/.m2/repository/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT.aar https://nexus-prod-mercury.dnitv.net/repository/maven-snapshots/com/facebook/fresco/imagepipeline-base/2.0.1-SNAPSHOT/imagepipeline-base-2.0.1-SNAPSHOT.aar
